In [1]:
import numpy as np

a = np.array([10, 20, 30, 40])


# Core Aggregation Functions

In [16]:
print(a.sum())
print(a.mean())
print(a.min())
print(a.max())
print(np.median(a))
print(np.std(a))
print(np.var(a))

170
42.5
10
90
35.0
31.12474899497183
968.75


# Aggregation on 2D Arrays

In [11]:
A = np.array([[10, 20, 30],
              [40, 50, 60]])
print(A.sum())
print(A.sum(axis=0))
print(A.sum(axis=1))
print(A.mean(axis=0))
print(A.mean(axis=1))
print(np.median(A,axis=1))
print(np.median(A,axis=0))


210
[50 70 90]
[ 60 150]
[25. 35. 45.]
[20. 50.]
[20. 50.]
[25. 35. 45.]


# Arg Functions

In [15]:
a = np.array([10,50,20,90])
print(a.argmax()) # show index of max value
print(a.argmin()) # show index of min value
print(A.argmax(axis=0))
print(A.argmin(axis=1))

3
0
[1 1 1]
[0 0]


# Cumulative Operations

In [23]:
a = np.array([10,20,30,40])

print(a.cumprod())
print(a.cumsum())
print(A.cumsum(axis=0))
print(A.cumprod(axis=0))
print(A.cumsum())

[    10    200   6000 240000]
[ 10  30  60 100]
[[10 20 30]
 [50 70 90]]
[[  10   20   30]
 [ 400 1000 1800]]
[ 10  30  60 100 150 210]


# NaN-Safe Aggregation (NaN = "Not a Number")

In [28]:
x = np.array([10,10,np.nan,40])

print(np.nanmean(x))
print(x.mean())
print(np.nansum(x))
print(np.nanprod(x))

20.0
nan
60.0
4000.0


# Exercise

In [33]:
a = np.arange(5,26,5)
print(a)
print(a.sum())
print(a.mean())
print(a.min())
print(a.max())
print(a.argmax())

[ 5 10 15 20 25]
75
15.0
5
25
4


In [34]:
A = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])
print(A.sum(axis=0))
print(A.sum(axis=1))
print(A.mean(axis=0))
print(A.mean(axis=1))

[120 150 180]
[ 60 150 240]
[40. 50. 60.]
[20. 50. 80.]


In [35]:
x = np.array([2, 4, 6, 8])
print(x.cumsum())
print(x.cumprod())

[ 2  6 12 20]
[  2   8  48 384]


In [37]:
y = np.array([10, np.nan, 30, 40])
print(np.nanmean(y))
print(np.nansum(y))

26.666666666666668
80.0
