# Starting Numpy 

In [2]:
import numpy as np 
##1D array
mat_1D = np.array([1,2,3,4,5,6,7,8,9,0])
print(mat_1D)


[1 2 3 4 5 6 7 8 9 0]


In [3]:
# np.arange(starting,ending,step)
mat_arange = np.arange(30,15,-1)
print(mat_arange)

[30 29 28 27 26 25 24 23 22 21 20 19 18 17 16]


## Creating array from scratch 

In [6]:
# zeros for creating zeros matric
mat_zeros = np.zeros((3,4))
print(mat_zeros)
# ones for creating ones matrix 
mat_ones = np.ones((2,3))
print(mat_ones)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [7]:
mat_full = np.full((3,5),7)
print(mat_full)

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


## Random function for creating random matrices

In [29]:
## np.random.random((block,row,column))
mat_random = np.random.random((2,3,2))
print(mat_random)

[[[0.32784921 0.88588346]
  [0.06590442 0.87477006]
  [0.67309729 0.0408896 ]]

 [[0.97875886 0.39315039]
  [0.3310563  0.12292358]
  [0.00209931 0.97454909]]]


## Array properties

In [35]:
mat_shape = mat_random.shape
print(mat_shape)

mat_dimension = mat_random.ndim
print(mat_dimension)

(2, 3, 2)
3


In [11]:
mat_dtype = mat_random.dtype
print(mat_dtype)

float64


## Array Reshaping 

In [36]:
print("mat_random shape before reshaping: ", mat_shape)
reshaped_mat_random = mat_random.reshape((2,2,3)) #(block,row,col)
reshape_shape = reshaped_mat_random.shape
print(reshaped_mat_random)
print("mat_random shape now :\n", reshape_shape)

mat_random shape before reshaping:  (2, 3, 2)
[[[0.32784921 0.88588346 0.06590442]
  [0.87477006 0.67309729 0.0408896 ]]

 [[0.97875886 0.39315039 0.3310563 ]
  [0.12292358 0.00209931 0.97454909]]]
mat_random shape now :
 (2, 2, 3)


In [55]:
arr_2d = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]
                ])
arr_dimen = arr_2d.ndim
arr_shape = arr_2d.shape
print(arr_shape)
print(arr_dimen)
## Array Transpose
transposed_arr = arr_2d.T
print("before Transpose:\n",arr_2d)
print("after Transpose: \n",transposed_arr)

(3, 3)
2
before Transpose:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
after Transpose: 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


## Numpy Array operation 

In [56]:
arr_2d = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]
                ])
print(arr_2d[1,2])  # access the element
print(arr_2d[1,:])  # access the row 
print(arr_2d[:,0])  # access the col
print(arr_2d[1])    # access the row

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6
[4 5 6]
[1 4 7]
[4 5 6]


In [53]:
# Sorting in 1d array
arr_1d = np.array([9,8,7,5,2,4])
sorted_arr_1d = np.sort(arr_1d)
print(sorted_arr_1d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 4 5 7 8 9]


In [62]:
# sorting in 2d array
arr_2d_unsorted = np.array([[3,1],
                            [1,2],
                            [4,3]]
                          )
print("before sorting: \n", arr_2d_unsorted)
arr_2d_sorted_col = np.sort(arr_2d_unsorted,axis=0) # column wise or vertical sorting 
print(arr_2d_sorted_col)
arr_2d_sorted_row = np.sort(arr_2d_unsorted,axis=1) # row wise or horizontal sorting
print(arr_2d_sorted_row)

before sorting: 
 [[3 1]
 [1 2]
 [4 3]]
[[1 1]
 [3 2]
 [4 3]]
[[1 3]
 [1 2]
 [3 4]]


## Filter

In [67]:
num = np.array([1,2,3,4,5,6,7,8,9,10])
even_num = num[num%2==0]
print(even_num)
odd_num = num[num%2!=0]
print(odd_num)

[ 2  4  6  8 10]
[1 3 5 7 9]


### Filter with mask 

In [69]:
mask = num>5
print(num[mask])
print(mask)

[ 6  7  8  9 10]
[False False False False False  True  True  True  True  True]


### Fancy indexing vs np.where()

In [72]:
indices = [0,2,4]
print(num[indices])

where_result = np.where(num>5)
print(num[where_result])

condition_array = np.where(num>5,num*4,num) # (condition,if,else)
print(condition_array)

[1 3 5]
[ 6  7  8  9 10]
[ 1  2  3  4  5 24 28 32 36 40]


## Adding & Removing Data

In [74]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
combined = arr1 + arr2 
print(combined)
combined = np.concatenate((arr1,arr2))
print(combined)

[5 7 9]
[1 2 3 4 5 6]


## Array Compatibility

In [77]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print("Compatibility shape:", a.shape == b.shape)

original = np.array([[1,2],
                     [3,4]])
new_row = np.array([[5,6]])
with_new_row = np.vstack((original, new_row))
print(with_new_row)

new_column = [[7],[8]]
with_new_column = np.hstack((original, new_column))
print(with_new_column)


Compatibility shape: True
[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]


In [79]:
arr = np.arange(1,6)
print(arr)

deleted = np.delete(arr,2) 
print(deleted)

[1 2 3 4 5]
[1 2 4 5]


In [ ]:
vectorize_