# Scalar Broadcasting

In [2]:
import numpy as np

a = np.array([1,2,3,4])
print(a+10)

[11 12 13 14]


# Broadcasting Between Arrays

In [3]:
a = np.array([1,2,3])
b = np.array([10])
print(a+b)

[11 12 13]


# Valid Broadcasting

In [5]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

v = np.array([10,20,30])
A + v


array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])

# Column Broadcasting

In [6]:
col = np.array([[10],
                [20],
                [30]])

A + col


array([[11, 12, 13],
       [24, 25, 26],
       [37, 38, 39]])

# Invalid Broadcasting


In [7]:
a = np.array([1,2,3])
b = np.array([10,20])
a + b


ValueError: operands could not be broadcast together with shapes (3,) (2,) 

# Broadcasting in Real Work

In [12]:
data = np.array([[10,20,30],
                 [40,50,60]])
mean = data.mean(axis=0)
print(mean)
normalized = data - mean
print(normalized)

[25. 35. 45.]
[[-15. -15. -15.]
 [ 15.  15.  15.]]


# Scale rows differently

In [13]:
weights = np.array(([1],
                    [2]))
print(data*weights)

[[ 10  20  30]
 [ 80 100 120]]


# Mini Exercise

In [15]:
# Set A:
a = np.array([1,2,3,4])
print(a+100)
print(a*-1)

[101 102 103 104]
[-1 -2 -3 -4]


In [17]:
# Set B;
A = np.array([[1,2,3],
              [4,5,6],
             ])
v = np.array([10,20,30])
print(A+v)


[[11 22 33]
 [14 25 36]]


In [18]:
# Set B:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
c = np.array([[10],
              [20],
              [30]])
print(c+A)
# c will be broadcasted throughout columns of A. And values of c will be added to each column correspondingly.


[[11 12 13]
 [24 25 26]
 [37 38 39]]
