In [3]:
import numpy as np
# section A
# 1:
arr_1d = np.arange(1,11)
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
# 2:
arr_2d = np.zeros((3,4))
print(arr_2d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
# 3:
arr_ones = np.ones((4,4))
print(arr_ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [8]:
# 4:
arr = np.arange(0,21)
print(arr)
mask = arr%2 == 0
even_arr = arr[mask]
print(even_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 0  2  4  6  8 10 12 14 16 18 20]


In [13]:
# 5:
print(np.linspace(0,1,5))

[0.   0.25 0.5  0.75 1.  ]


In [14]:
# 6:
print(np.eye(3,3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
# 7:
arr = np.array([[5, 10, 15],
                [20, 25, 30]])
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

2
(2, 3)
6
int64


In [16]:
# 8:
print(arr.itemsize)

8


In [21]:
# 9:
int_arr = np.array([1,2,3])
float_arr = int_arr.astype(float)
print(float_arr)

[1. 2. 3.]


In [28]:
# 10
mixed_arr = np.array([1,2.3,15])
print(mixed_arr.dtype)

float64


In [29]:
# 11:
print(np.array([1,2,3], dtype= float))

[1. 2. 3.]


In [27]:
a = np.array([2, 4, 6])
b = np.array([1, 3, 5])
# 12:
print(a+b)
# 13:
print(a-b)
# 14:
print(a*10)
# 15:
print(a/b)
# 16:
print(a*a)

[ 3  7 11]
[1 1 1]
[20 40 60]
[2.         1.33333333 1.2       ]
[ 4 16 36]


In [34]:
x = np.array([10, 20, 30, 40])
# 17:
mark = x>25
print(x[mark])
# 18:
print(x[x==20])
# 19:
bool_arr = np.where(x%10==0,True,False)
print(bool_arr)
print(x%10==0)

[30 40]
[20]
[ True  True  True  True]
[ True  True  True  True]


In [35]:
# 20:
# np.arange(1,5) give the array which contain integer from 1 to 4
# np.linspace(1,5,4) divide the gap between 1 and 5 into 4 number in a array form
# 21: numpy is faster than python because of it uses cpp for its function though programming happen in python.
# 22: Multiplying list by 3 will show list with element store 3 times in it. While Multiplying Numpy array by 3 cause all element multiplied by 3 individually.

In [36]:
num = np.arange(1,101)
print(num)
num = num*2
print(num)
num = num+5
print(num)
mask = num>150
print(num[mask])

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106 108
 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142 144
 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178 180
 182 184 186 188 190 192 194 196 198 200]
[  7   9  11  13  15  17  19  21  23  25  27  29  31  33  35  37  39  41
  43  45  47  49  51  53  55  57  59  61  63  65  67  69  71  73  75  77
  79  81  83  85  87  89  91  93  95  97