In [1]:
import numpy as np 
arr = np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
arr_linespace = np.linspace(0,10,5)
print(arr_linespace)

[ 0.   2.5  5.   7.5 10. ]


In [9]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
print(arr.size)
print(arr.itemsize)

10
8


In [14]:
print(arr)
print(np.array([1,2,3], dtype=float))
print(arr.astype(float))

[0 1 2 3 4 5 6 7 8 9]
[1. 2. 3.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [19]:
print(arr<15)

[ True  True  True  True  True  True  True  True  True  True]


In [20]:
print(arr==5)

[False False False False False  True False False False False]


In [22]:
print(arr+10*10)

[100 101 102 103 104 105 106 107 108 109]


In [24]:
oth = np.set_printoptions(precision = 2)
print(oth)

None
