In [3]:
import numpy as np

a = np.array([10,20,30,40,50])
print(a[0])
print(a[-1])
print(a[-5])

10
50
10


In [ ]:
print(a[1:4])
print(a[:3])
print(a[2:])
print(a[::2])
print(a[::-1])

[20 30 40]
[10 20 30]
[30 40 50]
[10 30 50]
[50 40 30 20 10]


In [ ]:
print(a)
c = a[1:4].copy()
c[0] = 888
print(a)
print(c)

[10 20 30 40 50]
[10 20 30 40 50]
[888  30  40]


In [7]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(arr[0:2, 1:3])
print(arr[0:2,:])


[[2 3]
 [5 6]]
[[1 2 3]
 [4 5 6]]


In [8]:
mat_1d = np.arange(100,500,100)
print(mat_1d)
idx = [0,2]
print(mat_1d[idx])

[100 200 300 400]
[100 300]


In [9]:
mat_1d[mat_1d>250] = 500
print(mat_1d)

[100 200 500 500]


In [14]:
arr = np.arange(5,35,5)
print(arr)
# Q1:
print(arr[1:4])
# Q2:
print(arr[-2:-5:-1])
# Q3:
arr[arr>20] = 999
print(arr)

[ 5 10 15 20 25 30]
[10 15 20]
[25 20 15]
[  5  10  15  20 999 999]


In [19]:
# Q4:
mat = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print(mat[1])
# Q5:
print(mat[:,2])
# Q6:
print(mat[0:2,1:3])

[4 5 6]
[3 6 9]
[[2 3]
 [5 6]]


In [22]:
x = np.array([12, 17, 21, 24, 30])
print(x[x%2==0])
print(x[x%3==0])
x[x<20]=0
print(x)

[12 24 30]
[12 21 24 30]
[ 0  0 21 24 30]
