# Dot product

In [3]:
import numpy as np
# check shape of a and b first.
a = np.array([1, 2, 3])
b = np.array([4,5,6])
print(np.dot(a,b))
print(a@b)

32
32


# Matrix Multiplication

In [5]:
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[1,2],
              [3,4],
              [5,6]])
print("is A and B compatilble: ",A.shape, B.shape)
print(A@B)

is A and B compatilble:  (2, 3) (3, 2)
[[22 28]
 [49 64]]


# Determinant

In [7]:
sqr_mat = np.array([[2,1],
                    [1,3]])
print(np.linalg.det(sqr_mat))

-2.0000000000000004


# Inverse

In [8]:
print(np.linalg.inv(sqr_mat))

[[-2.   1. ]
 [ 1.5 -0.5]]


# Solving Linear Equation

In [11]:
b = np.array([[5],[6]])
x = np.linalg.inv(sqr_mat)@b # don't use this as it is slower
print(x)
x = np.linalg.solve(sqr_mat,b)
print(x)

[[-4. ]
 [ 4.5]]
[[-4. ]
 [ 4.5]]


# Exercise

In [12]:
a = np.array([2,3])
b = np.array([4,5])
print(a@b)


23


In [14]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])
print(A@B)
print(A*B)

[[19 22]
 [43 50]]
[[ 5 12]
 [21 32]]


In [15]:
A = np.array([[2,1],
              [1,3]])
B = np.array([[5],[6]])
print(np.linalg.solve(A,B))

[[1.8]
 [1.4]]


In [20]:
X = np.array([[1,2,3],
              [4,5,6]])
print(X.shape)
Y = X.T
print(Y.shape)
print(Y)
# Row length become column width and vice-versa.

(2, 3)
(3, 2)
[[1 4]
 [2 5]
 [3 6]]
