In [5]:
import numpy as np
arr = [1,2,3,4,5,6]
vec = np.array(arr)
print("Python's List: ",arr)
print("Numpy's Array: ",vec)

Python's List:  [1, 2, 3, 4, 5, 6]
Numpy's Array:  [1 2 3 4 5 6]


In [16]:
mat_2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array in 2D:\n",mat_2D)
mat_1D = mat_2D.flatten()
print("Flattening of mat_2D: ",mat_1D)
flat = mat_2D.ravel()
print("Using ravel() : ",flat)
mat_Transpose = mat_2D.T
print("Transpose of mat_2D:\n",mat_Transpose)

Array in 2D:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Flattening of mat_2D:  [1 2 3 4 5 6 7 8 9]
Using ravel() :  [1 2 3 4 5 6 7 8 9]
Transpose of mat_2D:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


## Sorting 

In [23]:
unsorted_arr = np.array([[1,5,8],
                         [7,5,8],
                         [2,6,9]])
unsorted_arr = np.sort(unsorted_arr,axis=1)
print("row-wise sorting\n",unsorted_arr)
unsorted_arr = np.sort(unsorted_arr,axis=0)
print("col-wise sorting\n",unsorted_arr)

row-wise sorting
 [[1 5 8]
 [5 7 8]
 [2 6 9]]
col-wise sorting
 [[1 5 8]
 [2 6 8]
 [5 7 9]]


## Filter

In [24]:
num = np.array([1,2,3,4,5,6,7,8,9])
even_num = num[num%2 ==0]
print(even_num)

[2 4 6 8]


Filter with mask

In [26]:
mask = num>5
print(num[mask])

[6 7 8 9]


Fancy indexing vs np.where()

In [33]:
indices = [0,2,4]
print(num[indices])

where_result = np.where(num>5)
print(num[where_result])
condition_array = np.where(num>5,True,False)
print(condition_array)

[1 3 5]
[6 7 8 9]
[False False False False False  True  True  True  True]


## Adding and Removing Data

In [38]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
combined = arr1+arr2
print(combined)
combined = np.concatenate((arr1,arr2))
print(combined)

[5 7 9]
[1 2 3 4 5 6]


In [43]:
original = np.array([[1,2],[3,4]])
print(original)
new_row = np.array([[5,6]])
with_new_row = np.vstack((original,new_row))
print(with_new_row)
new_col = np.array([[5],[6]])
with_new_col = np.hstack((original,new_col))
print(with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]


In [45]:
before_del = np.array([1,2,3,4,5])
after_del = np.delete(before_del,2)
print(after_del)

[1 2 4 5]


Array Compatibility

In [48]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print("Compatibility shape", a.shape==b.shape)

Compatibility shape True
