In [1]:
import numpy as np

In [3]:
print(np.linspace(0,1,12,endpoint=True)[1:-1])

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.        ]


In [9]:
z = np.random.randint(0,10,size=10)
# a = np.sort(z)
z.sort()
print(z)

[1 1 1 3 6 7 8 8 8 9]


In [11]:
a = np.arange(10)
print(np.add.reduce(a))

45


In [14]:
A = np.random.randint(1,10,10)
print(A)
B = np.random.randint(1,10,10)
print(B)
print(np.allclose(A,B))
print(A==B)

[6 2 8 1 5 5 4 5 5 6]
[5 2 9 1 5 5 2 1 3 4]
False
[False  True False  True  True  True False False False False]


In [16]:
a = np.zeros(10)
a.flags.writeable = False
a[0] = -1

ValueError: assignment destination is read-only

In [17]:
z = np.random.random((10,2))
x, y = z[:,0], z[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
print(r)
print(t)

[1.10830466 0.0463702  0.99564634 0.53694804 0.86792153 0.56950377
 0.91875393 1.06596554 0.50223036 0.97462016]
[0.49641054 0.50698653 1.3886933  1.33091028 1.23518601 0.05942007
 0.28596436 0.68642248 1.51748438 1.27189572]


In [18]:
a = np.random.rand(10)
a[a.argmax()] = 0
print(a)

[0.         0.89056832 0.13131778 0.49917892 0.08430334 0.80050427
 0.49387587 0.1989345  0.62210768 0.81377741]


In [20]:
z = np.zeros((10,10),[('x',float),('y',float)])
print(z)
z['x'], z['y'] = np.meshgrid(np.linspace(0,1,10),np.linspace(0,1,10))
print("Upgraded: \n",z)

[[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]]
Upgraded: 
 [[(0.        , 0.        ) (0.1111111