In [72]:
import numpy as np

A = np.array([[4, 1, 7],
              [2, 9, 3],
              [6, 5, 8]])

In [73]:
# Q1
print(A[:,1:2])

[[1]
 [9]
 [5]]


In [74]:
# Q2
B = A[0:2,1:3]
print(B)

[[1 7]
 [9 3]]


In [75]:
# Q3
B[0,0] = 100
print(A)
print(B)
# A changed because of B. As B and A share same memory address. Any change in B which is view of A, A will also change its value


[[  4 100   7]
 [  2   9   3]
 [  6   5   8]]
[[100   7]
 [  9   3]]


In [76]:
# Q4:
print(A.sum(axis=1))

[111  14  19]


In [77]:
# Q5:
print(A.max(axis=0))


[  6 100   8]


In [78]:
# Q6:
sorted_indices = A.argsort(axis=1)
print(sorted_indices)

[[0 2 1]
 [0 2 1]
 [1 0 2]]


In [79]:
# Q7:

print(np.take_along_axis(A,sorted_indices,axis=1))

[[  4   7 100]
 [  2   3   9]
 [  5   6   8]]


In [80]:
# Q8:
nums = np.array([10,20,30])
print(A+nums)

[[ 14 120  37]
 [ 12  29  33]
 [ 16  25  38]]


In [82]:
sorted_col = A.argsort(axis=0)
print(np.take_along_axis(A,sorted_col,axis=0))
print(A)

[[  2   5   3]
 [  4   9   7]
 [  6 100   8]]
[[  4 100   7]
 [  2   9   3]
 [  6   5   8]]
