In [1]:
import numpy as np

In [ ]:
print(np.__version__)
config = np.show_config()
print(config)


2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name

In [ ]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
arr = np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
print(arr[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [ ]:
arr_2d = np.arange(0,9)
arr_2d = arr_2d.reshape(3,3)
print(arr_2d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


In [ ]:
id_mat = np.eye(3)
print(id_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
print(np.random.rand(3,3,3))
print(np.random.random(size=(3,3,3)))

[[[0.96564311 0.43836075 0.87156461]
  [0.64917721 0.4256059  0.46969303]
  [0.61836863 0.69399831 0.10118781]]

 [[0.85345552 0.02053582 0.11277422]
  [0.68249061 0.38448696 0.89029845]
  [0.31976203 0.96948132 0.25171447]]

 [[0.83659121 0.73867067 0.01821134]
  [0.86893514 0.99696533 0.94787465]
  [0.95358768 0.40065397 0.27976277]]]
[[[0.26627564 0.9684685  0.5070939 ]
  [0.08200487 0.17267595 0.91135503]
  [0.25320884 0.72663527 0.98258081]]

 [[0.5265731  0.12463166 0.01134589]
  [0.62919158 0.3660333  0.02462529]
  [0.77448944 0.65711862 0.46723404]]

 [[0.44986854 0.62415417 0.16436455]
  [0.99882502 0.72768825 0.4122673 ]
  [0.07832867 0.34175852 0.96875761]]]


In [ ]:
random_mat = np.random.random(size=(10,10))
print(random_mat)
print(np.max(random_mat),random_mat.max())
print(np.min(random_mat),random_mat.min())

[[0.1417767  0.67143841 0.19659027 0.19956411 0.04774297 0.43626006
  0.41132536 0.44785117 0.15934799 0.04785285]
 [0.55470851 0.63865418 0.1286347  0.44873185 0.18667472 0.52236537
  0.31736471 0.47983316 0.80462516 0.15434414]
 [0.36113113 0.79462746 0.24624188 0.98875913 0.79556491 0.0146339
  0.70524673 0.26086157 0.86056597 0.93051669]
 [0.1347136  0.14265748 0.22936815 0.53962779 0.64832317 0.16723228
  0.98285895 0.57067749 0.4431791  0.72974708]
 [0.34663803 0.38252322 0.12053902 0.96438    0.12436328 0.64050866
  0.51589338 0.13077912 0.30266877 0.92982198]
 [0.63395947 0.25547618 0.81740958 0.87394149 0.79051527 0.97647041
  0.004233   0.25812569 0.49327881 0.38562767]
 [0.49910544 0.75051342 0.47569976 0.06456071 0.00900887 0.25175037
  0.90650895 0.05983712 0.70417162 0.45835727]
 [0.02346786 0.79136089 0.90979297 0.66207449 0.6934095  0.5853208
  0.81658349 0.50842796 0.77028085 0.11751722]
 [0.70804565 0.57718073 0.64696997 0.54943844 0.00852556 0.52802932
  0.24110291 0

In [ ]:
random_vec = np.random.random(size=(30))
print(random_vec)
print(random_vec.mean())

[0.55340667 0.49559497 0.24817267 0.47086498 0.12202539 0.21288381
 0.42481062 0.74386244 0.46035221 0.26711972 0.97202814 0.98001897
 0.56368841 0.58210562 0.67172194 0.83592765 0.72820906 0.05358428
 0.21746647 0.89981331 0.85687309 0.95480248 0.6633145  0.9273338
 0.6752536  0.69925435 0.79036453 0.74396689 0.203508   0.42926321]
0.581586392611909


In [ ]:
z = np.ones((4,4))
# z[1,1] = 0
z[1:-1,1:-1]=0
print(z)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [ ]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

False

In [ ]:
diag = np.diag(1+np.arange(4),k=-1)
print(diag)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [ ]:
z = np.zeros((8,8),dtype = int)
z[::2,::2] = 1
z[1::2,1::2] = 1
print(z)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [ ]:
np.unravel_index(100,(6,7,8))

(np.int64(1), np.int64(5), np.int64(4))

In [ ]:
z = np.arange(1,10).reshape(3,3)
print(z)
z.ravel()
print(z.flatten())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [ ]:
z = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
a = np.tile(np.array([[1,2],[2,1]]),(4,4))
print(a)

[[1 2 1 2 1 2 1 2]
 [2 1 2 1 2 1 2 1]
 [1 2 1 2 1 2 1 2]
 [2 1 2 1 2 1 2 1]
 [1 2 1 2 1 2 1 2]
 [2 1 2 1 2 1 2 1]
 [1 2 1 2 1 2 1 2]
 [2 1 2 1 2 1 2 1]]


In [ ]:
z = np.random.randint(1,50,size=(5,5))
print(z)
zmax, zmin = z.max(), z.min()
z = (z - zmin)/(zmax - zmin)
print(z)

[[34 48 30 13 33]
 [12 15 17 46 48]
 [23 25 45 46 49]
 [48 31  8 16 10]
 [ 3 49 23 41 38]]
[[0.67391304 0.97826087 0.58695652 0.2173913  0.65217391]
 [0.19565217 0.26086957 0.30434783 0.93478261 0.97826087]
 [0.43478261 0.47826087 0.91304348 0.93478261 1.        ]
 [0.97826087 0.60869565 0.10869565 0.2826087  0.15217391]
 [0.         1.         0.43478261 0.82608696 0.76086957]]


In [ ]:
color = np.dtype([("r",np.ubyte,1),
                 ("g",np.ubyte,1),
                 ("b",np.ubyte,1),
                 ("a",np.ubyte,1)])
print(color)

[('r', 'u1', (1,)), ('g', 'u1', (1,)), ('b', 'u1', (1,)), ('a', 'u1', (1,))]


In [ ]:
a = np.arange(0,15).reshape(5,3)
print(a)
b = np.arange(0,6).reshape(3,2)
print(a@b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


In [ ]:
z = np.arange(11)
mask = (3 < z) & (z <= 8)
z[mask] *= -1
print(z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [ ]:
print(sum(range(5),-1)) # here sum is python inbuilt function and -1 show starting number
from numpy import *
print(sum(range(5),-1)) # -1 show last plane that is x
print(sum(a))


10
105


In [2]:
Z = np.random.randint(1,10,size=(2,2))
print(Z)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
# print(Z<Z>Z)

[[2 3]
 [9 6]]
[[        4        27]
 [387420489     46656]]
[[  2   4]
 [256  32]]
[[False False]
 [False False]]
[[0.+2.j 0.+3.j]
 [0.+9.j 0.+6.j]]
[[2. 3.]
 [9. 6.]]


In [5]:
print(np.array(0)//np.array(0))
print(np.array(0)//np.array(0.))
print(np.array(0)/np.array(0))
print(np.array(0)/np.array(0.))

0
nan
nan
nan


/tmp/ipython-input-1941423226.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0)//np.array(0))
/tmp/ipython-input-1941423226.py:2: RuntimeWarning: invalid value encountered in floor_divide
  print(np.array(0)//np.array(0.))
/tmp/ipython-input-1941423226.py:3: RuntimeWarning: invalid value encountered in divide
  print(np.array(0)/np.array(0))
/tmp/ipython-input-1941423226.py:4: RuntimeWarning: invalid value encountered in divide
  print(np.array(0)/np.array(0.))


In [6]:
print(np.eye(4, k=1))

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [7]:
z = np.random.randint(-10,10,10)
print(np.trunc(z + np.copysign(0.5,z)))


[ -2.   4.   1.   1.   6.  -9.   3.  -3.  -4. -10.]


In [14]:
z = np.random.uniform(0,10,10)
print(z)
print(z-z%1)
print(np.floor(z))
print(np.ceil(z)-1)
print(z.astype(int))
print(np.trunc(z))

[3.424642   7.47308608 2.24232793 3.85390545 8.92022425 5.88345238
 5.92338754 8.3095592  3.02718803 4.63778973]
[3. 7. 2. 3. 8. 5. 5. 8. 3. 4.]
[3. 7. 2. 3. 8. 5. 5. 8. 3. 4.]
[3. 7. 2. 3. 8. 5. 5. 8. 3. 4.]
[3 7 2 3 8 5 5 8 3 4]
[3. 7. 2. 3. 8. 5. 5. 8. 3. 4.]


In [15]:
print(np.random.randint(0,4,(5,5)))

[[2 0 3 2 1]
 [1 2 0 2 0]
 [3 3 3 2 0]
 [3 1 2 0 0]
 [1 1 0 3 3]]


In [19]:
z = np.zeros((5,5))
z += np.arange(5)
print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [21]:
def generate():
  for x in range(10):
    yield x
z = np.fromiter(generate(),dtype=float,count=-1)
print(z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
