# Random Numbers

In [1]:
import numpy as np
# rand() give values in [0,1)
print(np.random.rand(5))
print(np.random.rand(2,3))

[0.1916561  0.26653105 0.70280798 0.53662487 0.67577771]
[[0.57891428 0.75127872 0.53987195]
 [0.93291407 0.60726797 0.40034026]]


In [ ]:
# randn() give standard normal distribution
# mean = ~0 , Std = ~1
print(np.random.randn(5))

[-0.40360101 -1.84027863  0.17064309 -0.7014257  -0.58386103]


# Random Integers

In [ ]:
print(np.random.randint(1,10))
print(np.random.randint(1,10,size=5))
print(np.random.randint(1,10,size=(2,3)))

3
[4 5 5 9 1]
[[5 1 2]
 [6 4 7]]


# Probability Distribution

In [ ]:
# Normal distribution
print(np.random.normal(loc=50,scale=5,size=5))

# Uniform distribution
print(np.random.uniform(0,100,size=5))

# Binomial distribution
print(np.random.binomial(n=10,p=0.5,size=5))

[48.75073784 44.76945135 57.03776745 42.60873692 53.11875767]
[41.21214666 48.05333663  8.54688188 20.25213712 80.53152225]
[6 6 2 4 5]


# Reproducibility(seed)

In [12]:
np.random.seed(42)
print(np.random.rand(3))

[0.37454012 0.95071431 0.73199394]


# Shuffling Data

In [21]:
# Shuffle array(in-place)
a = np.array([1,2,3,4,5])
np.random.shuffle(a)
print(a)
print(np.random.permutation(a))


[1 2 5 4 3]
[2 4 3 5 1]


# Random Sampling

In [25]:
choice = np.random.choice([10,20,30,40],size=2)
print(choice)
# With probabilities:
choice = np.random.choice([0,1],size=10,p=[0.7,0.3])
print(choice)



[10 40]
[0 0 0 0 0 0 0 1 0 0]


# Exercise:

In [28]:
print(np.random.rand(10))
print(np.random.randint(1,50,size=(3,3)))

[0.727272   0.32654077 0.57044397 0.52083426 0.96117202 0.84453385
 0.74732011 0.53969213 0.58675117 0.96525531]
[[45 41 29]
 [15 45  1]
 [25  7  9]]


In [29]:
print(np.random.randn(100))

[-0.676922    0.61167629  1.03099952  0.93128012 -0.83921752 -0.30921238
  0.33126343  0.97554513 -0.47917424 -0.18565898 -1.10633497 -1.19620662
  0.81252582  1.35624003 -0.07201012  1.0035329   0.36163603 -0.64511975
  0.36139561  1.53803657 -0.03582604  1.56464366 -2.6197451   0.8219025
  0.08704707 -0.29900735  0.09176078 -1.98756891 -0.21967189  0.35711257
  1.47789404 -0.51827022 -0.8084936  -0.50175704  0.91540212  0.32875111
 -0.5297602   0.51326743  0.09707755  0.96864499 -0.70205309 -0.32766215
 -0.39210815 -1.46351495  0.29612028  0.26105527  0.00511346 -0.23458713
 -1.41537074 -0.42064532 -0.34271452 -0.80227727 -0.16128571  0.40405086
  1.8861859   0.17457781  0.25755039 -0.07444592 -1.91877122 -0.02651388
  0.06023021  2.46324211 -0.19236096  0.30154734 -0.03471177 -1.16867804
  1.14282281  0.75193303  0.79103195 -0.90938745  1.40279431 -1.40185106
  0.58685709  2.19045563 -0.99053633 -0.56629773  0.09965137 -0.50347565
 -1.55066343  0.06856297 -1.06230371  0.47359243 -0.

In [30]:
np.random.seed(50)
print(np.random.rand(5))

[0.49460165 0.2280831  0.25547392 0.39632991 0.3773151 ]


In [37]:
arr = np.array([1,2,3,4,5])
print(np.random.permutation(arr))
choice = np.random.choice([10,20,30,40,50])
print(choice)

[5 2 1 3 4]
30
