# Using reshape()

In [6]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])
a = a.reshape(2,3)
print(a)
a = a.reshape(3,2)
print(a)
print(a.reshape(2, -1))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]


# Flattening Arrays


In [ ]:
A = np.array([[1,2,3],
              [4,5,6]])
# ravel():
print(A.ravel())
# flatten():
print(A.flatten())


[1 2 3 4 5 6]
[1 2 3 4 5 6]


# Transpose


In [ ]:
print(A.T)
print(A.shape)
print(A.T.shape)

[[1 4]
 [2 5]
 [3 6]]
(2, 3)
(3, 2)


# Axis Awareness

In [3]:
A = np.array([[1,2,3],
              [4,5,6]])
print(A.sum())
print(A.sum(axis=0)) # vertical or column-wise
print(A.sum(axis=1)) # horizontal or row wise

21
[5 7 9]
[ 6 15]


# Stacking Arrays

In [ ]:
# Vertical stack or for adding row
print(np.vstack([A,[1,2,3]]))

# Horizontal stack or for adding column
print(np.hstack([[[0],[0]],A]))

[[1 2 3]
 [4 5 6]
 [1 2 3]]
[[0 1 2 3]
 [0 4 5 6]]


# Splitting Arrays


In [10]:
print(np.split(a,3)) # for 1-D array.
print(np.hsplit(A,3))
print(np.vsplit(A,2))

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]
[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]
[array([[1, 2, 3]]), array([[4, 5, 6]])]


# Exercise

In [16]:
a = np.arange(1,13)
print(a.reshape(3,4))
print(a.reshape(4,3))
print(a.reshape(2,-1))
print(a.reshape(-1,6))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [19]:
A = np.array([[1,2,3],
              [4,5,6]])
print(A.ravel())
print(A.flatten())
print(A.T)

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]


In [20]:
B = np.array([[10,20,30],
              [40,50,60],
              [70,80,90]])
print(B.sum(axis=0))
print(B.sum(axis=1))

[120 150 180]
[ 60 150 240]


In [23]:
X = np.array([[1,2],
              [3,4]])
print(np.vstack([X,[[0,1],[0,2]]]))
print(np.hstack([X,[[9],[9]]]))

[[1 2]
 [3 4]
 [0 1]
 [0 2]]
[[1 2 9]
 [3 4 9]]
