# Sorting Basics

In [2]:
import numpy as np

a = np.array([40, 10, 30, 20])
print(np.sort(a)) # safe copy
print(a)
a.sort() # return modified original
print(a)

[10 20 30 40]
[40 10 30 20]
[10 20 30 40]


# Sorting 2D Arrays

In [4]:
A = np.array([[30,10,20],
              [60,40,50]])
print(np.sort(A,axis=1))
print(np.sort(A,axis=0))

[[10 20 30]
 [40 50 60]]
[[30 10 20]
 [60 40 50]]


# Sorting by Index

In [7]:
a = np.array([40,10,30,20])
idx = np.argsort(a)
print(idx)
print(a[idx])

[1 3 2 0]
[10 20 30 40]


# Sorting Real Pattern

In [9]:
scores = np.array([88,92,79,95])
names = np.array(["A","B","C","D"])

order = np.argsort(scores)
print(names[order])
print(scores[order])

['C' 'A' 'B' 'D']
[79 88 92 95]


# Searching Basics

In [10]:
x = np.array([10,20,30,40,50])
idx = np.where(x>25)
print(x[idx])

[30 40 50]


# Location of Non-Zero Elements

In [11]:
a = np.array([0,5,0,10])
non_zero_idx = np.nonzero(a)
print(a[non_zero_idx])


[ 5 10]


# Membership Testing

In [12]:
a = np.array([10,20,30,40])
b = np.array([20,40])

print(np.isin(a, b))

[False  True False  True]


# Unique Values

In [15]:
x = np.array([1,2,2,3,3,3,4,4,5,5,5,6,7])
print(np.unique(x))
vals, counts = np.unique(x, return_counts=True)
print(vals)
print(counts)

[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7]
[1 2 3 2 3 1 1]


# Set Opertion

In [20]:
a = np.arange(1,5)
b = np.arange(3,7)
print(a,b)
print(np.union1d(a,b))
print(np.intersect1d(a,b))
print(np.setdiff1d(a,b))
print(np.setxor1d(a,b))

[1 2 3 4] [3 4 5 6]
[1 2 3 4 5 6]
[3 4]
[1 2]
[1 2 5 6]


# Exercise

In [25]:
a = np.array([45, 10, 35, 20])
print(np.sort(a))
idx = np.argsort(a)
print(idx)
print(a[idx])

[10 20 35 45]
[1 3 2 0]
[10 20 35 45]


In [27]:
A = np.array([[8,3,5],
             [4,9,1]])
print(np.sort(A,axis=1))
print(np.sort(A,axis=0))


[[3 5 8]
 [1 4 9]]
[[4 3 1]
 [8 9 5]]


In [29]:
x = np.array([12, 18, 25, 30, 42])
print(x[x>20])
mask = np.where(x%6==0)
print(mask)

[25 30 42]
(array([0, 1, 3, 4]),)


In [34]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([4, 5, 6, 7])
print(np.union1d(a,b))
print(np.intersect1d(a,b))
print(np.setdiff1d(a,b))

[1 2 3 4 5 6 7]
[4 5]
[1 2 3]
